[tool.briefcase]
project_name = "Peringkasan Text Otomatis"
bundle = "com.frsnmk.peringkasantext"
version = "0.0.1"
url = "https://peringkasantext.frsnmk.com/peringkasantext"
license = "BSD license"
author = 'frsnmk'
author_email = "razedman@gmail.com"

[tool.briefcase.app.peringkasantext]
formal_name = "Peringkasan Text"
description = "Aplikasi Peringkasan Text Otomatis menggunakan metode CLSA"
icon = "src/peringkasantext/resources/peringkasantext"
sources = ['src/peringkasantext']
requires = [
    'nltk==3.5',
    'numpy==1.19.3',
    'Sastrawi==1.0.1'
]


[tool.briefcase.app.peringkasantext.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.peringkasantext.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.peringkasantext.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.peringkasantext.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.peringkasantext.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
